trigger: none
jobs:
  - job: DownloadRepo
    displayName: 'Download repo'
    variables:
      workingDir: '$(System.DefaultWorkingDirectory)\'
      dxFeedVar: '$(DXFeed)'
      NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: PowerShell@2
      inputs:
        filePath: '$(workingDir)\Start.ps1'
        showWarnings: true
        failOnStderr: true
        pwsh: true
      env:
        apobekiarisToken: $(apobekiarisToken)
        DxFeed: $(DxFeed)
